on:
  push:
  pull_request:

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, armv7l]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t messense/manylinux2014-cross:${{ matrix.arch }} -f ${{ matrix.arch }}.Dockerfile .
      - name: Alias armv7l to armv7
        if: matrix.arch == 'armv7l'
        run: |
          docker tag messense/manylinux2014-cross:armv7l messense/manylinux2014-cross:armv7
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push messense/manylinux2014-cross:${{ matrix.arch }}
