name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-armv7:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push armv7
      uses: docker/build-push-action@v3
      with:
        context: manylinux_2_28/armv7l/
        push: true
        tags: congyuwang/manylinux_2_28-cross:armv7

  build-aarch64:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push aarch64
      uses: docker/build-push-action@v3
      with:
        context: manylinux_2_28/aarch64/
        push: true
        tags: congyuwang/manylinux_2_28-cross:aarch64
