name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-x86-64:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push aarch64
      uses: docker/build-push-action@v3
      with:
        context: manylinux2014/x86_64_not_cross
        push: true
        tags: congyuwang/manylinux2014:x86_64

